/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kasir;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adan Nugraha
 */
public class FormDetailTransaksi extends javax.swing.JFrame {
    private DefaultTableModel tabmode;
    private ResultSet hasilDetail;
    /**
     * Creates new form FormDetailTransaksi
     */
    public FormDetailTransaksi(String idTransaksi) {
        Riwayat riwayat = new Riwayat();
        initComponents();
        lblIdTransaksi.setText(idTransaksi);
        Object [] detailTransaksi = {"Nomor", "Nama Barang", "Jumlah Barang", "Total Harga"};
        tabmode = new DefaultTableModel(null, detailTransaksi);
        tabelDetail.setModel(tabmode);
        try {
            hasilDetail = riwayat.tampilDetail( (String) idTransaksi);
            int i = 1;
            while (hasilDetail.next()) {
                riwayat.setNamaBarang(hasilDetail.getString("nama_barang"));
                riwayat.setJumlahBarang(hasilDetail.getString("jumlah_barang"));
                riwayat.setTotalHarga(hasilDetail.getString("total_harga"));
                String[] dataDetail = {Integer.toString(i), riwayat.getNamaBarang(), riwayat.getJumlahBarang(),
                                            riwayat.getTotalHarga()};
                i++;
                tabmode.addRow(dataDetail);
            }
        } catch (NumberFormatException | SQLException e) {
            
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelDetail = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblIdTransaksi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabelDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nomor", "Nama Barang", "Jumlah Barang", "Total Harga"
            }
        ));
        tabelDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDetailMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelDetail);

        jLabel1.setText("ID Transaksi :");

        lblIdTransaksi.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jLabel1)
                        .addGap(93, 93, 93)
                        .addComponent(lblIdTransaksi)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblIdTransaksi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FormRiwayat formRiwayat = new FormRiwayat();
        dispose();
        formRiwayat.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabelDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDetailMouseClicked
        
    }//GEN-LAST:event_tabelDetailMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblIdTransaksi;
    private javax.swing.JTable tabelDetail;
    // End of variables declaration//GEN-END:variables
}
